apiVersion: v1
kind: Service
metadata:
    name: deploy
    namespace: deploy
    labels:
        app: deploy
spec:
    selector:
        app: deploy
    type: NodePort
    ports:
        - name: http
          port: 80
          targetPort: 80
          nodePort: 30200
