apiVersion: skaffold/v1
kind: Config
build:
    artifacts:
        - image: lokeshkarakala/deploy
          context: ../deploy
          jib: {}
    tagPolicy:
        envTemplate:
            template: '{{.IMAGE_NAME}}:latest'
deploy:
    kustomize: {}
